### ISSUE TITLE
안녕하세요. 안드로이드 스튜디오, 자바 초짜인데 이 코드를 어떻게 복사해서 실행시킬 수 있는지 여쭤보고싶습니다. 

### ISSUE THREAD

**Issue by mkjeong0** [ivorycirrus/pedometer#1]

**Comment by ivorycirrus** [comment]
안년하세요
강필모입니다

안드로이드 프로젝트는 일부 파일만 복사한다고 모든기능이 동작하진 않습니다

빌드 환경이나 실행환걍 라이브러리종속성 등을 함께 보셔야합니다

전체 프로젝트를 clone하셔서 실행 해 보신 후
하나하나 변경해 가며 학습하시길 추천드립니다

감사합니다




2018년 6월 2일 (토) 오후 10:55, mkjeong0 <notifications@github.com>님이 작성:
